all:
	gcc remote_login.c inet_sockets.c pty_master_open.c pty_fork.c tty_functions.c -o remote_login
	gcc remote_client.c inet_sockets.c pty_master_open.c pty_fork.c tty_functions.c -o remote_client
	gcc unbuffer.c inet_sockets.c pty_master_open.c pty_fork.c tty_functions.c -o unbuffer

